/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hiido.hva.thrift.protocol;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-10-13")
public class SignupService {

  public interface Iface {

    public SignupReply signup(int companyId, String companyName, int userId) throws com.hiido.hcat.thrift.protocol.AuthorizationException, com.hiido.hcat.thrift.protocol.RuntimeException, org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void signup(int companyId, String companyName, int userId, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public SignupReply signup(int companyId, String companyName, int userId) throws com.hiido.hcat.thrift.protocol.AuthorizationException, com.hiido.hcat.thrift.protocol.RuntimeException, org.apache.thrift.TException
    {
      send_signup(companyId, companyName, userId);
      return recv_signup();
    }

    public void send_signup(int companyId, String companyName, int userId) throws org.apache.thrift.TException
    {
      signup_args args = new signup_args();
      args.setCompanyId(companyId);
      args.setCompanyName(companyName);
      args.setUserId(userId);
      sendBase("signup", args);
    }

    public SignupReply recv_signup() throws com.hiido.hcat.thrift.protocol.AuthorizationException, com.hiido.hcat.thrift.protocol.RuntimeException, org.apache.thrift.TException
    {
      signup_result result = new signup_result();
      receiveBase(result, "signup");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.authException != null) {
        throw result.authException;
      }
      if (result.runTimeException != null) {
        throw result.runTimeException;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "signup failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void signup(int companyId, String companyName, int userId, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      signup_call method_call = new signup_call(companyId, companyName, userId, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class signup_call extends org.apache.thrift.async.TAsyncMethodCall {
      private int companyId;
      private String companyName;
      private int userId;
      public signup_call(int companyId, String companyName, int userId, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.companyId = companyId;
        this.companyName = companyName;
        this.userId = userId;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("signup", org.apache.thrift.protocol.TMessageType.CALL, 0));
        signup_args args = new signup_args();
        args.setCompanyId(companyId);
        args.setCompanyName(companyName);
        args.setUserId(userId);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public SignupReply getResult() throws com.hiido.hcat.thrift.protocol.AuthorizationException, com.hiido.hcat.thrift.protocol.RuntimeException, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_signup();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("signup", new signup());
      return processMap;
    }

    public static class signup<I extends Iface> extends org.apache.thrift.ProcessFunction<I, signup_args> {
      public signup() {
        super("signup");
      }

      public signup_args getEmptyArgsInstance() {
        return new signup_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public signup_result getResult(I iface, signup_args args) throws org.apache.thrift.TException {
        signup_result result = new signup_result();
        try {
          result.success = iface.signup(args.companyId, args.companyName, args.userId);
        } catch (com.hiido.hcat.thrift.protocol.AuthorizationException authException) {
          result.authException = authException;
        } catch (com.hiido.hcat.thrift.protocol.RuntimeException runTimeException) {
          result.runTimeException = runTimeException;
        }
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("signup", new signup());
      return processMap;
    }

    public static class signup<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, signup_args, SignupReply> {
      public signup() {
        super("signup");
      }

      public signup_args getEmptyArgsInstance() {
        return new signup_args();
      }

      public AsyncMethodCallback<SignupReply> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<SignupReply>() { 
          public void onComplete(SignupReply o) {
            signup_result result = new signup_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            signup_result result = new signup_result();
            if (e instanceof com.hiido.hcat.thrift.protocol.AuthorizationException) {
                        result.authException = (com.hiido.hcat.thrift.protocol.AuthorizationException) e;
                        result.setAuthExceptionIsSet(true);
                        msg = result;
            }
            else             if (e instanceof com.hiido.hcat.thrift.protocol.RuntimeException) {
                        result.runTimeException = (com.hiido.hcat.thrift.protocol.RuntimeException) e;
                        result.setRunTimeExceptionIsSet(true);
                        msg = result;
            }
             else 
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, signup_args args, org.apache.thrift.async.AsyncMethodCallback<SignupReply> resultHandler) throws TException {
        iface.signup(args.companyId, args.companyName, args.userId,resultHandler);
      }
    }

  }

  public static class signup_args implements org.apache.thrift.TBase<signup_args, signup_args._Fields>, java.io.Serializable, Cloneable, Comparable<signup_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("signup_args");

    private static final org.apache.thrift.protocol.TField COMPANY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("companyId", org.apache.thrift.protocol.TType.I32, (short)1);
    private static final org.apache.thrift.protocol.TField COMPANY_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("companyName", org.apache.thrift.protocol.TType.STRING, (short)2);
    private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("userId", org.apache.thrift.protocol.TType.I32, (short)3);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new signup_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new signup_argsTupleSchemeFactory());
    }

    public int companyId; // required
    public String companyName; // required
    public int userId; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      COMPANY_ID((short)1, "companyId"),
      COMPANY_NAME((short)2, "companyName"),
      USER_ID((short)3, "userId");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // COMPANY_ID
            return COMPANY_ID;
          case 2: // COMPANY_NAME
            return COMPANY_NAME;
          case 3: // USER_ID
            return USER_ID;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __COMPANYID_ISSET_ID = 0;
    private static final int __USERID_ISSET_ID = 1;
    private byte __isset_bitfield = 0;
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.COMPANY_ID, new org.apache.thrift.meta_data.FieldMetaData("companyId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
      tmpMap.put(_Fields.COMPANY_NAME, new org.apache.thrift.meta_data.FieldMetaData("companyName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("userId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(signup_args.class, metaDataMap);
    }

    public signup_args() {
    }

    public signup_args(
      int companyId,
      String companyName,
      int userId)
    {
      this();
      this.companyId = companyId;
      setCompanyIdIsSet(true);
      this.companyName = companyName;
      this.userId = userId;
      setUserIdIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public signup_args(signup_args other) {
      __isset_bitfield = other.__isset_bitfield;
      this.companyId = other.companyId;
      if (other.isSetCompanyName()) {
        this.companyName = other.companyName;
      }
      this.userId = other.userId;
    }

    public signup_args deepCopy() {
      return new signup_args(this);
    }

    @Override
    public void clear() {
      setCompanyIdIsSet(false);
      this.companyId = 0;
      this.companyName = null;
      setUserIdIsSet(false);
      this.userId = 0;
    }

    public int getCompanyId() {
      return this.companyId;
    }

    public signup_args setCompanyId(int companyId) {
      this.companyId = companyId;
      setCompanyIdIsSet(true);
      return this;
    }

    public void unsetCompanyId() {
      __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __COMPANYID_ISSET_ID);
    }

    /** Returns true if field companyId is set (has been assigned a value) and false otherwise */
    public boolean isSetCompanyId() {
      return EncodingUtils.testBit(__isset_bitfield, __COMPANYID_ISSET_ID);
    }

    public void setCompanyIdIsSet(boolean value) {
      __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __COMPANYID_ISSET_ID, value);
    }

    public String getCompanyName() {
      return this.companyName;
    }

    public signup_args setCompanyName(String companyName) {
      this.companyName = companyName;
      return this;
    }

    public void unsetCompanyName() {
      this.companyName = null;
    }

    /** Returns true if field companyName is set (has been assigned a value) and false otherwise */
    public boolean isSetCompanyName() {
      return this.companyName != null;
    }

    public void setCompanyNameIsSet(boolean value) {
      if (!value) {
        this.companyName = null;
      }
    }

    public int getUserId() {
      return this.userId;
    }

    public signup_args setUserId(int userId) {
      this.userId = userId;
      setUserIdIsSet(true);
      return this;
    }

    public void unsetUserId() {
      __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __USERID_ISSET_ID);
    }

    /** Returns true if field userId is set (has been assigned a value) and false otherwise */
    public boolean isSetUserId() {
      return EncodingUtils.testBit(__isset_bitfield, __USERID_ISSET_ID);
    }

    public void setUserIdIsSet(boolean value) {
      __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __USERID_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case COMPANY_ID:
        if (value == null) {
          unsetCompanyId();
        } else {
          setCompanyId((Integer)value);
        }
        break;

      case COMPANY_NAME:
        if (value == null) {
          unsetCompanyName();
        } else {
          setCompanyName((String)value);
        }
        break;

      case USER_ID:
        if (value == null) {
          unsetUserId();
        } else {
          setUserId((Integer)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case COMPANY_ID:
        return getCompanyId();

      case COMPANY_NAME:
        return getCompanyName();

      case USER_ID:
        return getUserId();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case COMPANY_ID:
        return isSetCompanyId();
      case COMPANY_NAME:
        return isSetCompanyName();
      case USER_ID:
        return isSetUserId();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof signup_args)
        return this.equals((signup_args)that);
      return false;
    }

    public boolean equals(signup_args that) {
      if (that == null)
        return false;

      boolean this_present_companyId = true;
      boolean that_present_companyId = true;
      if (this_present_companyId || that_present_companyId) {
        if (!(this_present_companyId && that_present_companyId))
          return false;
        if (this.companyId != that.companyId)
          return false;
      }

      boolean this_present_companyName = true && this.isSetCompanyName();
      boolean that_present_companyName = true && that.isSetCompanyName();
      if (this_present_companyName || that_present_companyName) {
        if (!(this_present_companyName && that_present_companyName))
          return false;
        if (!this.companyName.equals(that.companyName))
          return false;
      }

      boolean this_present_userId = true;
      boolean that_present_userId = true;
      if (this_present_userId || that_present_userId) {
        if (!(this_present_userId && that_present_userId))
          return false;
        if (this.userId != that.userId)
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_companyId = true;
      list.add(present_companyId);
      if (present_companyId)
        list.add(companyId);

      boolean present_companyName = true && (isSetCompanyName());
      list.add(present_companyName);
      if (present_companyName)
        list.add(companyName);

      boolean present_userId = true;
      list.add(present_userId);
      if (present_userId)
        list.add(userId);

      return list.hashCode();
    }

    @Override
    public int compareTo(signup_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetCompanyId()).compareTo(other.isSetCompanyId());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetCompanyId()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.companyId, other.companyId);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetCompanyName()).compareTo(other.isSetCompanyName());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetCompanyName()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.companyName, other.companyName);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetUserId()).compareTo(other.isSetUserId());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetUserId()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userId, other.userId);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("signup_args(");
      boolean first = true;

      sb.append("companyId:");
      sb.append(this.companyId);
      first = false;
      if (!first) sb.append(", ");
      sb.append("companyName:");
      if (this.companyName == null) {
        sb.append("null");
      } else {
        sb.append(this.companyName);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("userId:");
      sb.append(this.userId);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class signup_argsStandardSchemeFactory implements SchemeFactory {
      public signup_argsStandardScheme getScheme() {
        return new signup_argsStandardScheme();
      }
    }

    private static class signup_argsStandardScheme extends StandardScheme<signup_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, signup_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // COMPANY_ID
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.companyId = iprot.readI32();
                struct.setCompanyIdIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // COMPANY_NAME
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.companyName = iprot.readString();
                struct.setCompanyNameIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // USER_ID
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.userId = iprot.readI32();
                struct.setUserIdIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, signup_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        oprot.writeFieldBegin(COMPANY_ID_FIELD_DESC);
        oprot.writeI32(struct.companyId);
        oprot.writeFieldEnd();
        if (struct.companyName != null) {
          oprot.writeFieldBegin(COMPANY_NAME_FIELD_DESC);
          oprot.writeString(struct.companyName);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldBegin(USER_ID_FIELD_DESC);
        oprot.writeI32(struct.userId);
        oprot.writeFieldEnd();
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class signup_argsTupleSchemeFactory implements SchemeFactory {
      public signup_argsTupleScheme getScheme() {
        return new signup_argsTupleScheme();
      }
    }

    private static class signup_argsTupleScheme extends TupleScheme<signup_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, signup_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetCompanyId()) {
          optionals.set(0);
        }
        if (struct.isSetCompanyName()) {
          optionals.set(1);
        }
        if (struct.isSetUserId()) {
          optionals.set(2);
        }
        oprot.writeBitSet(optionals, 3);
        if (struct.isSetCompanyId()) {
          oprot.writeI32(struct.companyId);
        }
        if (struct.isSetCompanyName()) {
          oprot.writeString(struct.companyName);
        }
        if (struct.isSetUserId()) {
          oprot.writeI32(struct.userId);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, signup_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.companyId = iprot.readI32();
          struct.setCompanyIdIsSet(true);
        }
        if (incoming.get(1)) {
          struct.companyName = iprot.readString();
          struct.setCompanyNameIsSet(true);
        }
        if (incoming.get(2)) {
          struct.userId = iprot.readI32();
          struct.setUserIdIsSet(true);
        }
      }
    }

  }

  public static class signup_result implements org.apache.thrift.TBase<signup_result, signup_result._Fields>, java.io.Serializable, Cloneable, Comparable<signup_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("signup_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);
    private static final org.apache.thrift.protocol.TField AUTH_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("authException", org.apache.thrift.protocol.TType.STRUCT, (short)1);
    private static final org.apache.thrift.protocol.TField RUN_TIME_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("runTimeException", org.apache.thrift.protocol.TType.STRUCT, (short)2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new signup_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new signup_resultTupleSchemeFactory());
    }

    public SignupReply success; // required
    public com.hiido.hcat.thrift.protocol.AuthorizationException authException; // required
    public com.hiido.hcat.thrift.protocol.RuntimeException runTimeException; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      AUTH_EXCEPTION((short)1, "authException"),
      RUN_TIME_EXCEPTION((short)2, "runTimeException");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // AUTH_EXCEPTION
            return AUTH_EXCEPTION;
          case 2: // RUN_TIME_EXCEPTION
            return RUN_TIME_EXCEPTION;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SignupReply.class)));
      tmpMap.put(_Fields.AUTH_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("authException", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
      tmpMap.put(_Fields.RUN_TIME_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("runTimeException", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(signup_result.class, metaDataMap);
    }

    public signup_result() {
    }

    public signup_result(
      SignupReply success,
      com.hiido.hcat.thrift.protocol.AuthorizationException authException,
      com.hiido.hcat.thrift.protocol.RuntimeException runTimeException)
    {
      this();
      this.success = success;
      this.authException = authException;
      this.runTimeException = runTimeException;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public signup_result(signup_result other) {
      if (other.isSetSuccess()) {
        this.success = new SignupReply(other.success);
      }
      if (other.isSetAuthException()) {
        this.authException = new com.hiido.hcat.thrift.protocol.AuthorizationException(other.authException);
      }
      if (other.isSetRunTimeException()) {
        this.runTimeException = new com.hiido.hcat.thrift.protocol.RuntimeException(other.runTimeException);
      }
    }

    public signup_result deepCopy() {
      return new signup_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
      this.authException = null;
      this.runTimeException = null;
    }

    public SignupReply getSuccess() {
      return this.success;
    }

    public signup_result setSuccess(SignupReply success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public com.hiido.hcat.thrift.protocol.AuthorizationException getAuthException() {
      return this.authException;
    }

    public signup_result setAuthException(com.hiido.hcat.thrift.protocol.AuthorizationException authException) {
      this.authException = authException;
      return this;
    }

    public void unsetAuthException() {
      this.authException = null;
    }

    /** Returns true if field authException is set (has been assigned a value) and false otherwise */
    public boolean isSetAuthException() {
      return this.authException != null;
    }

    public void setAuthExceptionIsSet(boolean value) {
      if (!value) {
        this.authException = null;
      }
    }

    public com.hiido.hcat.thrift.protocol.RuntimeException getRunTimeException() {
      return this.runTimeException;
    }

    public signup_result setRunTimeException(com.hiido.hcat.thrift.protocol.RuntimeException runTimeException) {
      this.runTimeException = runTimeException;
      return this;
    }

    public void unsetRunTimeException() {
      this.runTimeException = null;
    }

    /** Returns true if field runTimeException is set (has been assigned a value) and false otherwise */
    public boolean isSetRunTimeException() {
      return this.runTimeException != null;
    }

    public void setRunTimeExceptionIsSet(boolean value) {
      if (!value) {
        this.runTimeException = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((SignupReply)value);
        }
        break;

      case AUTH_EXCEPTION:
        if (value == null) {
          unsetAuthException();
        } else {
          setAuthException((com.hiido.hcat.thrift.protocol.AuthorizationException)value);
        }
        break;

      case RUN_TIME_EXCEPTION:
        if (value == null) {
          unsetRunTimeException();
        } else {
          setRunTimeException((com.hiido.hcat.thrift.protocol.RuntimeException)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      case AUTH_EXCEPTION:
        return getAuthException();

      case RUN_TIME_EXCEPTION:
        return getRunTimeException();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case AUTH_EXCEPTION:
        return isSetAuthException();
      case RUN_TIME_EXCEPTION:
        return isSetRunTimeException();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof signup_result)
        return this.equals((signup_result)that);
      return false;
    }

    public boolean equals(signup_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      boolean this_present_authException = true && this.isSetAuthException();
      boolean that_present_authException = true && that.isSetAuthException();
      if (this_present_authException || that_present_authException) {
        if (!(this_present_authException && that_present_authException))
          return false;
        if (!this.authException.equals(that.authException))
          return false;
      }

      boolean this_present_runTimeException = true && this.isSetRunTimeException();
      boolean that_present_runTimeException = true && that.isSetRunTimeException();
      if (this_present_runTimeException || that_present_runTimeException) {
        if (!(this_present_runTimeException && that_present_runTimeException))
          return false;
        if (!this.runTimeException.equals(that.runTimeException))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      boolean present_authException = true && (isSetAuthException());
      list.add(present_authException);
      if (present_authException)
        list.add(authException);

      boolean present_runTimeException = true && (isSetRunTimeException());
      list.add(present_runTimeException);
      if (present_runTimeException)
        list.add(runTimeException);

      return list.hashCode();
    }

    @Override
    public int compareTo(signup_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetAuthException()).compareTo(other.isSetAuthException());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAuthException()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.authException, other.authException);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetRunTimeException()).compareTo(other.isSetRunTimeException());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetRunTimeException()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.runTimeException, other.runTimeException);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("signup_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("authException:");
      if (this.authException == null) {
        sb.append("null");
      } else {
        sb.append(this.authException);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("runTimeException:");
      if (this.runTimeException == null) {
        sb.append("null");
      } else {
        sb.append(this.runTimeException);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class signup_resultStandardSchemeFactory implements SchemeFactory {
      public signup_resultStandardScheme getScheme() {
        return new signup_resultStandardScheme();
      }
    }

    private static class signup_resultStandardScheme extends StandardScheme<signup_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, signup_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new SignupReply();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // AUTH_EXCEPTION
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.authException = new com.hiido.hcat.thrift.protocol.AuthorizationException();
                struct.authException.read(iprot);
                struct.setAuthExceptionIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // RUN_TIME_EXCEPTION
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.runTimeException = new com.hiido.hcat.thrift.protocol.RuntimeException();
                struct.runTimeException.read(iprot);
                struct.setRunTimeExceptionIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, signup_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.authException != null) {
          oprot.writeFieldBegin(AUTH_EXCEPTION_FIELD_DESC);
          struct.authException.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.runTimeException != null) {
          oprot.writeFieldBegin(RUN_TIME_EXCEPTION_FIELD_DESC);
          struct.runTimeException.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class signup_resultTupleSchemeFactory implements SchemeFactory {
      public signup_resultTupleScheme getScheme() {
        return new signup_resultTupleScheme();
      }
    }

    private static class signup_resultTupleScheme extends TupleScheme<signup_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, signup_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetAuthException()) {
          optionals.set(1);
        }
        if (struct.isSetRunTimeException()) {
          optionals.set(2);
        }
        oprot.writeBitSet(optionals, 3);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
        if (struct.isSetAuthException()) {
          struct.authException.write(oprot);
        }
        if (struct.isSetRunTimeException()) {
          struct.runTimeException.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, signup_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.success = new SignupReply();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.authException = new com.hiido.hcat.thrift.protocol.AuthorizationException();
          struct.authException.read(iprot);
          struct.setAuthExceptionIsSet(true);
        }
        if (incoming.get(2)) {
          struct.runTimeException = new com.hiido.hcat.thrift.protocol.RuntimeException();
          struct.runTimeException.read(iprot);
          struct.setRunTimeExceptionIsSet(true);
        }
      }
    }

  }

}
