/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hiido.hcat.thrift.protocol;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum JobStatus implements org.apache.thrift.TEnum {
  READY(0),
  RUNNING(1),
  COMPLETE(2),
  FAILURE(3),
  DEAD(4),
  HBTIMEOUT(5),
  CANCEL(6);

  private final int value;

  private JobStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JobStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return READY;
      case 1:
        return RUNNING;
      case 2:
        return COMPLETE;
      case 3:
        return FAILURE;
      case 4:
        return DEAD;
      case 5:
        return HBTIMEOUT;
      case 6:
        return CANCEL;
      default:
        return null;
    }
  }
}
