/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hiido.hcat.thrift.protocol;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-06-23")
public class QueryStatus implements org.apache.thrift.TBase<QueryStatus, QueryStatus._Fields>, java.io.Serializable, Cloneable, Comparable<QueryStatus> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("QueryStatus");

  private static final org.apache.thrift.protocol.TField CIPHER_FIELD_DESC = new org.apache.thrift.protocol.TField("cipher", org.apache.thrift.protocol.TType.MAP, (short)1);
  private static final org.apache.thrift.protocol.TField QUERY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("queryId", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new QueryStatusStandardSchemeFactory());
    schemes.put(TupleScheme.class, new QueryStatusTupleSchemeFactory());
  }

  public Map<String,String> cipher; // required
  public String queryId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CIPHER((short)1, "cipher"),
    QUERY_ID((short)2, "queryId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CIPHER
          return CIPHER;
        case 2: // QUERY_ID
          return QUERY_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CIPHER, new org.apache.thrift.meta_data.FieldMetaData("cipher", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.QUERY_ID, new org.apache.thrift.meta_data.FieldMetaData("queryId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(QueryStatus.class, metaDataMap);
  }

  public QueryStatus() {
  }

  public QueryStatus(
    Map<String,String> cipher,
    String queryId)
  {
    this();
    this.cipher = cipher;
    this.queryId = queryId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QueryStatus(QueryStatus other) {
    if (other.isSetCipher()) {
      Map<String,String> __this__cipher = new HashMap<String,String>(other.cipher);
      this.cipher = __this__cipher;
    }
    if (other.isSetQueryId()) {
      this.queryId = other.queryId;
    }
  }

  public QueryStatus deepCopy() {
    return new QueryStatus(this);
  }

  @Override
  public void clear() {
    this.cipher = null;
    this.queryId = null;
  }

  public int getCipherSize() {
    return (this.cipher == null) ? 0 : this.cipher.size();
  }

  public void putToCipher(String key, String val) {
    if (this.cipher == null) {
      this.cipher = new HashMap<String,String>();
    }
    this.cipher.put(key, val);
  }

  public Map<String,String> getCipher() {
    return this.cipher;
  }

  public QueryStatus setCipher(Map<String,String> cipher) {
    this.cipher = cipher;
    return this;
  }

  public void unsetCipher() {
    this.cipher = null;
  }

  /** Returns true if field cipher is set (has been assigned a value) and false otherwise */
  public boolean isSetCipher() {
    return this.cipher != null;
  }

  public void setCipherIsSet(boolean value) {
    if (!value) {
      this.cipher = null;
    }
  }

  public String getQueryId() {
    return this.queryId;
  }

  public QueryStatus setQueryId(String queryId) {
    this.queryId = queryId;
    return this;
  }

  public void unsetQueryId() {
    this.queryId = null;
  }

  /** Returns true if field queryId is set (has been assigned a value) and false otherwise */
  public boolean isSetQueryId() {
    return this.queryId != null;
  }

  public void setQueryIdIsSet(boolean value) {
    if (!value) {
      this.queryId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CIPHER:
      if (value == null) {
        unsetCipher();
      } else {
        setCipher((Map<String,String>)value);
      }
      break;

    case QUERY_ID:
      if (value == null) {
        unsetQueryId();
      } else {
        setQueryId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CIPHER:
      return getCipher();

    case QUERY_ID:
      return getQueryId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CIPHER:
      return isSetCipher();
    case QUERY_ID:
      return isSetQueryId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QueryStatus)
      return this.equals((QueryStatus)that);
    return false;
  }

  public boolean equals(QueryStatus that) {
    if (that == null)
      return false;

    boolean this_present_cipher = true && this.isSetCipher();
    boolean that_present_cipher = true && that.isSetCipher();
    if (this_present_cipher || that_present_cipher) {
      if (!(this_present_cipher && that_present_cipher))
        return false;
      if (!this.cipher.equals(that.cipher))
        return false;
    }

    boolean this_present_queryId = true && this.isSetQueryId();
    boolean that_present_queryId = true && that.isSetQueryId();
    if (this_present_queryId || that_present_queryId) {
      if (!(this_present_queryId && that_present_queryId))
        return false;
      if (!this.queryId.equals(that.queryId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_cipher = true && (isSetCipher());
    list.add(present_cipher);
    if (present_cipher)
      list.add(cipher);

    boolean present_queryId = true && (isSetQueryId());
    list.add(present_queryId);
    if (present_queryId)
      list.add(queryId);

    return list.hashCode();
  }

  @Override
  public int compareTo(QueryStatus other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCipher()).compareTo(other.isSetCipher());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCipher()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cipher, other.cipher);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQueryId()).compareTo(other.isSetQueryId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQueryId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.queryId, other.queryId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QueryStatus(");
    boolean first = true;

    sb.append("cipher:");
    if (this.cipher == null) {
      sb.append("null");
    } else {
      sb.append(this.cipher);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("queryId:");
    if (this.queryId == null) {
      sb.append("null");
    } else {
      sb.append(this.queryId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (cipher == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'cipher' was not present! Struct: " + toString());
    }
    if (queryId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'queryId' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QueryStatusStandardSchemeFactory implements SchemeFactory {
    public QueryStatusStandardScheme getScheme() {
      return new QueryStatusStandardScheme();
    }
  }

  private static class QueryStatusStandardScheme extends StandardScheme<QueryStatus> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, QueryStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CIPHER
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map30 = iprot.readMapBegin();
                struct.cipher = new HashMap<String,String>(2*_map30.size);
                String _key31;
                String _val32;
                for (int _i33 = 0; _i33 < _map30.size; ++_i33)
                {
                  _key31 = iprot.readString();
                  _val32 = iprot.readString();
                  struct.cipher.put(_key31, _val32);
                }
                iprot.readMapEnd();
              }
              struct.setCipherIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // QUERY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.queryId = iprot.readString();
              struct.setQueryIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, QueryStatus struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.cipher != null) {
        oprot.writeFieldBegin(CIPHER_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.cipher.size()));
          for (Map.Entry<String, String> _iter34 : struct.cipher.entrySet())
          {
            oprot.writeString(_iter34.getKey());
            oprot.writeString(_iter34.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.queryId != null) {
        oprot.writeFieldBegin(QUERY_ID_FIELD_DESC);
        oprot.writeString(struct.queryId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QueryStatusTupleSchemeFactory implements SchemeFactory {
    public QueryStatusTupleScheme getScheme() {
      return new QueryStatusTupleScheme();
    }
  }

  private static class QueryStatusTupleScheme extends TupleScheme<QueryStatus> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, QueryStatus struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.cipher.size());
        for (Map.Entry<String, String> _iter35 : struct.cipher.entrySet())
        {
          oprot.writeString(_iter35.getKey());
          oprot.writeString(_iter35.getValue());
        }
      }
      oprot.writeString(struct.queryId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, QueryStatus struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TMap _map36 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
        struct.cipher = new HashMap<String,String>(2*_map36.size);
        String _key37;
        String _val38;
        for (int _i39 = 0; _i39 < _map36.size; ++_i39)
        {
          _key37 = iprot.readString();
          _val38 = iprot.readString();
          struct.cipher.put(_key37, _val38);
        }
      }
      struct.setCipherIsSet(true);
      struct.queryId = iprot.readString();
      struct.setQueryIdIsSet(true);
    }
  }

}

